// Copyright 2016 Sam Whited.
// Use of this source code is governed by the BSD 2-clause license that can be
// found in the LICENSE file.

package sasl

import (
	"errors"
)

var (
	ErrInvalidState = errors.New("Invalid state")
	ErrAuthn        = errors.New("Authentication error")
	ErrAuthz        = errors.New("Authorization error")
	ErrTooManySteps = errors.New("Step called too many times")
)

// State represents the current state of a Mechanism's underlying state machine.
type State int8

const (
	Initial State = iota
	AuthTextSent
	ResponseSent
	ValidServerResponse
)

// Mechanism represents a SASL mechanism.
//
// A Mechanism is stateful and therefore should not be shared between
// goroutines.
type Mechanism struct {
	Name  string
	Start func(state State) ([]byte, error)
	Next  func(challenge []byte) ([]byte, error)

	state State
	err   error
}

// Step attempts to transition the SASL mechanism to its next state. If Step is
// called after a previous invocation generates an error (and the Mechanism has
// not been reset to its initial state), Step panics.
func (m *Mechanism) Step(challenge []byte) ([]byte, error) {
	if m.Err() != nil {
		panic(m.Err())
	}

	switch m.state {
	case Initial:
		r, err := m.Start(m.state)
		if err != nil {
			m.err = err
			return r, err
		}
		m.state = AuthTextSent
		return r, nil
	case AuthTextSent:
	case ResponseSent:
	case ValidServerResponse:
	}

	return nil, ErrInvalidState
}

// Err returns any errors generated by the SASL mechanism.
func (m *Mechanism) Err() error {
	return m.err
}

// State returns the internal state of the SASL mechanism.
func (m *Mechanism) State() State {
	return m.state
}
